# -*- coding: utf-8 -*-
"""ML_Assign2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DPX1SNU3dUsqOkDWVXPm3A7Dgv6e42Sf
"""

#Archita Jain
#102203613
#3CO14

import pandas as pd
import numpy as np

data = {
    'Name': ['A','B','C','D','E','F','G','H','I','J'],
    'Age': [11, 16, 15, 20, 21, 22, 25, 30, 35, 29],
    'Gender': ['F', 'M', 'F', 'F', 'M', 'M', 'M', 'F', 'F', 'F'],
    'Address': ['Paris', 'Barcelona', 'Tokyo', 'Delhi', 'New York', 'Chicago', 'Beijing', 'Seoul', 'Mumbai', 'Kolkata']
}
df = pd.DataFrame(data)
df

df.iloc[4]
df.iloc[1:4]
df.iloc[:]
df.iloc[1:4 , 5:8]

condition1 = df[df['Age'] >=25]
print(condition1)

df['Adult'] = df['Age'] > 18                   #Condition based on age and add a column
print(df)

filtered_df = df[(df['Gender'] == 'F') & (df['Age'] > 20)]
print(filtered_df)

df['Gender'].replace({'F' : "Female",'M': 'Male'}, inplace = True)       #No new dataframe is created. Original DataFrame modified --> INPLACE = TRUE
print (df)

df.rename(columns = {'Name' : 'Full Name'}, inplace = True)
print(df)

print("Maximum age is : " , df['Age'].max())
print("Minimum age is : " , df['Age'].min())
print("Sum of age is : " , df['Age'].sum())
print("Mean of age is : " , df['Age'].mean())
print("Counter of age is : " , df['Age'].count())

print(df['Gender'].unique())       #Unique values in Gender column
print(df['Gender'].nunique())      #Number of unique Values
print(df['Gender'].value_counts())

#df.drop(['Age'],axis=1, inplace = True)
print (df)
#df.drop(df.columns[1],axis=1, inplace = True)
print(df)

unique_df = df.drop_duplicates()
print(unique_df)

print(df[df['Gender']!='Male'])

print(df.groupby('Gender'))

for name in df['Full Name']:
  print(name.upper())

sqrt_age = df['Age'].apply(np.sqrt)                          #Make sure to impor numpy
print(sqrt_age)

group_count = df.groupby('Gender').apply(lambda x: x.count)
print(group_count)